"""Update models

Revision ID: 2492d83d2a92
Revises: 
Create Date: 2023-05-13 11:57:53.141505

"""
from alembic import op
import sqlalchemy as sa
import models

# revision identifiers, used by Alembic.
revision = '2492d83d2a92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=8), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('dueDate', sa.Date(), nullable=True),
    sa.Column('status', models.models.Status(), nullable=True),
    sa.Column('type', models.models.Type(), nullable=True),
    sa.Column('studentId', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['studentId'], ['student.studentId'], name='fk_invoice_student', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('password')

    op.drop_table('invoice')
    # ### end Alembic commands ###
