"""empty message

Revision ID: 73f1f2e93afd
Revises: fb41d0a34cc4
Create Date: 2023-05-13 16:35:58.553139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73f1f2e93afd'
down_revision = 'fb41d0a34cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('OUTSTANDING', 'PAID', 'CANCELLED'),
               type_=sa.String(length=15),
               existing_nullable=True,
               existing_server_default=sa.text("'OUTSTANDING'"))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.ENUM('COURSE_FEE', 'LIBRARY_FEE'), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.String(length=15),
               type_=mysql.ENUM('OUTSTANDING', 'PAID', 'CANCELLED'),
               existing_nullable=True,
               existing_server_default=sa.text("'OUTSTANDING'"))

    # ### end Alembic commands ###
