"""Update models

Revision ID: 9b4d98a18671
Revises: 2492d83d2a92
Create Date: 2023-05-13 12:25:27.239181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic.
import models;
revision = '9b4d98a18671'
down_revision = '2492d83d2a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.TINYTEXT(),
               type_=models.models.Status(),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=mysql.TINYTEXT(),
               type_=models.models.Type(),
               existing_nullable=True)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=models.models.Type(),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=models.models.Status(),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
