"""Update models

Revision ID: fb41d0a34cc4
Revises: 2583bf356bca
Create Date: 2023-05-13 16:27:16.881266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb41d0a34cc4'
down_revision = '2583bf356bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('OUTSTANDING', 'PAID', 'CANCELLED'),
               nullable=True,
               existing_server_default=sa.text("'OUTSTANDING'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('OUTSTANDING', 'PAID', 'CANCELLED'),
               nullable=False,
               existing_server_default=sa.text("'OUTSTANDING'"))

    # ### end Alembic commands ###
